//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Users {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblUserID;
		protected global::System.Web.UI.WebControls.TextBox txtUsername;
		protected global::System.Web.UI.WebControls.TextBox txtUserPassword;
		protected global::System.Web.UI.WebControls.TextBox txtUserRealName;
		protected global::System.Web.UI.WebControls.TextBox txtUserSex;
		protected global::System.Web.UI.WebControls.TextBox txtUserEmail;
		protected global::System.Web.UI.WebControls.TextBox txtUserGrade;
		protected global::System.Web.UI.WebControls.TextBox txtUserScore;
		protected global::System.Web.UI.WebControls.TextBox txtProvince;
		protected global::System.Web.UI.WebControls.TextBox txtCity;
		protected global::System.Web.UI.WebControls.TextBox txtAddress1;
		protected global::System.Web.UI.WebControls.TextBox txtUserIdentity;
		protected global::System.Web.UI.WebControls.TextBox txtRegistTime;
		protected global::System.Web.UI.WebControls.TextBox txtPhone;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
