//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Users {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblUserID;
	protected global::System.Web.UI.WebControls.Label lblUsername;
	protected global::System.Web.UI.WebControls.Label lblUserPassword;
	protected global::System.Web.UI.WebControls.Label lblUserRealName;
	protected global::System.Web.UI.WebControls.Label lblUserSex;
	protected global::System.Web.UI.WebControls.Label lblUserEmail;
	protected global::System.Web.UI.WebControls.Label lblUserGrade;
	protected global::System.Web.UI.WebControls.Label lblUserScore;
	protected global::System.Web.UI.WebControls.Label lblProvince;
	protected global::System.Web.UI.WebControls.Label lblCity;
	protected global::System.Web.UI.WebControls.Label lblAddress1;
	protected global::System.Web.UI.WebControls.Label lblUserIdentity;
	protected global::System.Web.UI.WebControls.Label lblRegistTime;
	protected global::System.Web.UI.WebControls.Label lblPhone;


       
    }
}
