//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Orders {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblOrderID;
	protected global::System.Web.UI.WebControls.Label lblUserID;
	protected global::System.Web.UI.WebControls.Label lblOrderDate;
	protected global::System.Web.UI.WebControls.Label lblOrderState;
	protected global::System.Web.UI.WebControls.Label lblCommodityID;
	protected global::System.Web.UI.WebControls.Label lblOrderNumber;
	protected global::System.Web.UI.WebControls.Label lblAddresseeName;
	protected global::System.Web.UI.WebControls.Label lblAddresseeAddress;
	protected global::System.Web.UI.WebControls.Label lblAddresseeZipCode;
	protected global::System.Web.UI.WebControls.Label lblAddresseePhone;
	protected global::System.Web.UI.WebControls.Label lblTotalMoney;
	protected global::System.Web.UI.WebControls.Label lblPayType;
	protected global::System.Web.UI.WebControls.Label lblDelivery;
	protected global::System.Web.UI.WebControls.Label lblMessage;
	protected global::System.Web.UI.WebControls.Label lblOrderImage;
	protected global::System.Web.UI.WebControls.Label lblCommodityName;
	protected global::System.Web.UI.WebControls.Label lblPrice;


       
    }
}
