//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Assn {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblAssnID;
		protected global::System.Web.UI.WebControls.TextBox txtSocialName;
		protected global::System.Web.UI.WebControls.TextBox txtSocialTeacher;
		protected global::System.Web.UI.WebControls.TextBox txtSocialLogo;
		protected global::System.Web.UI.WebControls.TextBox txtAddTime;
		protected global::System.Web.UI.WebControls.TextBox txtSocialState;
		protected global::System.Web.UI.WebControls.TextBox txtSocialPurpose;
		protected global::System.Web.UI.WebControls.TextBox txtSocialType;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
