//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Assn {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblAssnID;
	protected global::System.Web.UI.WebControls.Label lblSocialName;
	protected global::System.Web.UI.WebControls.Label lblSocialTeacher;
	protected global::System.Web.UI.WebControls.Label lblSocialLogo;
	protected global::System.Web.UI.WebControls.Label lblAddTime;
	protected global::System.Web.UI.WebControls.Label lblSocialState;
	protected global::System.Web.UI.WebControls.Label lblSocialPurpose;
	protected global::System.Web.UI.WebControls.Label lblSocialType;


       
    }
}
