//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Commodity {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtCommodityID;
		protected global::System.Web.UI.WebControls.TextBox txtCommodityFatherID;
		protected global::System.Web.UI.WebControls.TextBox txtCommoditySonID;
		protected global::System.Web.UI.WebControls.TextBox txtCommodityName;
		protected global::System.Web.UI.WebControls.TextBox txtCommodityPrice;
		protected global::System.Web.UI.WebControls.TextBox txtMarketPrice;
		protected global::System.Web.UI.WebControls.TextBox txtVIPPrice;
		protected global::System.Web.UI.WebControls.TextBox txtStock;
		protected global::System.Web.UI.WebControls.TextBox txtBuyScore;
		protected global::System.Web.UI.WebControls.TextBox txtCommodityImage;
		protected global::System.Web.UI.WebControls.TextBox txtCommodityType;
		protected global::System.Web.UI.WebControls.TextBox txtCommoditySaled;
		protected global::System.Web.UI.WebControls.TextBox txtIntroduce;
		protected global::System.Web.UI.WebControls.TextBox txtCommodityTime;
		protected global::System.Web.UI.WebControls.TextBox txtRecommend;
		protected global::System.Web.UI.WebControls.TextBox txtCommodityState;
		protected global::System.Web.UI.WebControls.TextBox txtScore;
		protected global::System.Web.UI.WebControls.TextBox txtScoreTimes;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
