//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Commodity {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCommodityID;
	protected global::System.Web.UI.WebControls.Label lblCommodityFatherID;
	protected global::System.Web.UI.WebControls.Label lblCommoditySonID;
	protected global::System.Web.UI.WebControls.Label lblCommodityName;
	protected global::System.Web.UI.WebControls.Label lblCommodityPrice;
	protected global::System.Web.UI.WebControls.Label lblMarketPrice;
	protected global::System.Web.UI.WebControls.Label lblVIPPrice;
	protected global::System.Web.UI.WebControls.Label lblStock;
	protected global::System.Web.UI.WebControls.Label lblBuyScore;
	protected global::System.Web.UI.WebControls.Label lblCommodityImage;
	protected global::System.Web.UI.WebControls.Label lblCommodityType;
	protected global::System.Web.UI.WebControls.Label lblCommoditySaled;
	protected global::System.Web.UI.WebControls.Label lblIntroduce;
	protected global::System.Web.UI.WebControls.Label lblCommodityTime;
	protected global::System.Web.UI.WebControls.Label lblRecommend;
	protected global::System.Web.UI.WebControls.Label lblCommodityState;
	protected global::System.Web.UI.WebControls.Label lblScore;
	protected global::System.Web.UI.WebControls.Label lblScoreTimes;


       
    }
}
