//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.OrderDetail {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblOrderDetailID;
		protected global::System.Web.UI.WebControls.TextBox txtOrderID;
		protected global::System.Web.UI.WebControls.TextBox txtCommodityID;
		protected global::System.Web.UI.WebControls.TextBox txtUserID;
		protected global::System.Web.UI.WebControls.TextBox txtOrderNumber;
		protected global::System.Web.UI.WebControls.TextBox txtAppraiseGrade;
		protected global::System.Web.UI.WebControls.TextBox txtSubtotal;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
